#!/bin/bash

if [ -f .env ]; then
  set -a
  source .env
  set +a
fi

export WWWGROUP="${WWWGROUP:-$(id -g)}"
export WWWUSER="${WWWUSER:-$(id -u)}"

if [ "$1" = "artisan" ]; then
  shift
  docker compose -f docker-compose.yml -f docker.override.yml \
    exec --user $(id -u):$(id -g) laravel-api php artisan "$@"
  exit
fi

docker compose -f docker-compose.yml -f docker.override.yml "$@"
